### ISSUE TITLE
Module fails if codedeploy-agent is manually uninstalled

### ISSUE THREAD

**Issue by kyl191** [walkamongus/puppet-codedeploy#5]
I'm running RHEL7, and just ran into an issue where the module fails if I use the module to install the codedeploy agent, I manually install it, and I try to use the module to reinstall the codedeploy agent.

If I manually reinstall the codedeploy agent, subsequent runs work fine.

```
Error: Execution of '/bin/yum -d 0 -e 0 -y list codedeploy-agent' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Codedeploy::Install/Package[codedeploy-agent]/ensure: change from absent to present failed: Execution of '/bin/yum -d 0 -e 0 -y list codedeploy-agent' returned 1: Error: No matching Packages to list
Notice: /Stage[main]/Codedeploy::Service/Service[codedeploy-agent]: Dependency Package[codedeploy-agent] has failures: true
Warning: /Stage[main]/Codedeploy::Service/Service[codedeploy-agent]: Skipping because of failed dependencies
```

**Comment by walkamongus** [comment]
So you are installing the RPM via the module, then manually uninstalling it and then running the module to re-install it is failing -- is that correct?

**Comment by kyl191** [comment]
Seemingly so - I managed to replicate it on two RHEL installs before just setting up a normal RPM package resource

**Comment by walkamongus** [comment]
I just located a bug causing this during testing. I'll push a fix to the forge shortly.

Thanks for finding this!

**Comment by walkamongus** [comment]
Release v1.0.1, pushed to the forge, fixes this. Note that its technically a backwards incompatible release as I removed some management of Ruby for Debian-based boxes. But your case will be unaffected.

The updated README notes the external dependency on Ruby and suggests satisfying it with the puppetlabs/ruby module.

Let me know if you have any issues!
